sudo: required

services: docker

before_install:
  - docker login -u $tk634 -p $dckr_pat_Powu7AJDp9-1bigUMHTyRl8DL6U
  - docker-compose up --build -d

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test

dist: trusty
